### ISSUE TITLE
Can't open udemy.com my course page

### ISSUE THREAD

**Issue by adamkenway007** [MoonchildProductions/UXP#1449]
i'm use pale moon from 2018-2020 but can't open my course page from udemy.com i don't know why.i must use original firefox/chrome to open course on udemy.please fix this bug.i want learn from udemy

**Comment by wolfbeast** [comment]
> Someone who has time (i.e. not me) will have to register, submit to being spammed by getting a free course, and check what's going on here.

**Comment by adamkenway007** [comment]
> 
> 
> > Someone who has time (i.e. not me) will have to register, submit to being spammed by getting a free course, and check what's going on here.

Sorry for late response,i'm currently used pale moon 28.9.0.2 bug still occur

this is latest pale moon while open udemy.com/course => no course  
![Capture](https://user-images.githubusercontent.com/24690518/78361752-1a732080-75e3-11ea-9932-a1a44398ce2a.PNG)

this is while i'm using firefox and chrome work as normally

![Capture1](https://user-images.githubusercontent.com/24690518/78361944-6cb44180-75e3-11ea-972e-fc419804511b.PNG)

could you please fix bug on next update please @wolfbeast  @mattatobin 
i don't like firefox because too heavy on my low end hardware laptop while open 5 page,while when i use pale moon i could open tab as much possible 10 tab onward

**Comment by wolfbeast** [comment]
Screenshots don't help.

**Comment by adamkenway007** [comment]
> Screenshots don't help.

Then,What should i do,to give more error information?
Normally page must be load view all purchased courses.but in this case courses not displayed correctly.
this bug only occur on browser with unified xul platform (uxp) such as pale moon and basilisk

**Comment by mattatobin** [comment]
Neither of us are gonna join telegram and please stop highlighting us specifically. I have nothing to add to this issue but get notifications to any updates you don't need to type my name.

**Comment by win7-7** [comment]
This website works in Pale Moon 28.4 but starting from version 28.5 it doesn't work anymore/menu doesn't work in website after login. I used temporary email to register to test this website.

Line 32993 seems be this: t&&Function.prototype.apply.call

from web console:

entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:32293
TypeError: t.sort is not a function
Stack trace:
o@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy.761d4ff6bd0f9fc4d050.js:1:382385
value@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy.761d4ff6bd0f9fc4d050.js:1:271539
Ss@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:1084455
xs@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:1084252
Cs@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:1088090
Fi@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:1111915
Bi@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:1112299
Sa@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:1119327
wa@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:1118707
Oa@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:1119803
Ge@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:663666
$e@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:663249
Ue@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:659546
le@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:650462
ue@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:650412
ut@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:664842
e/<@https://www.udemy.com/staticx/udemy/js/webpack/my-courses-v3-app.93d9f162924922da5f0d.js:1:627549
v@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:1276277
m/s._invoke</<@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:1276032
g/</e[t]@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:1276454
s@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:91643
a@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:95802
i@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:265600
D/<@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:265745
l@https://www.udemy.com/staticx/udemy/js/webpack/entry-main-legacy-vendor.2b217bfaaf03b312eae9.js:1:212494

So this is javascript regression.

**Comment by wolfbeast** [comment]
it's a minified webpack blob. it's not possible to troubleshoot from our side.

**Comment by win7-7** [comment]
Regression is caused by https://github.com/MoonchildProductions/UXP/commit/cd0e94ceb1031a76dc8e9f70bb9cdab691fb8866

This is one commit out of many of https://github.com/MoonchildProductions/UXP/pull/1002

However other commits related to pull 1002 do not cause regression.

Tested by compiling from source code. 

Previous commit https://github.com/MoonchildProductions/UXP/commit/04c16841227708a6037acb14ba506f0981481e37 does work with https://www.udemy.com/home/my-courses/learning/

**Comment by wolfbeast** [comment]
@JustOff this was your work, could you have a look at this please?

**Comment by JustOff** [comment]
I have already tried to deal with this last weekend, but unfortunately I did not succeed. Perhaps someone's fresh look could help.

**Comment by mattatobin** [comment]
And to whom would you suggest?

**Comment by wolfbeast** [comment]
The thing is this needs some time to research the issue. it's one of two scenarios:
- The code changes made us spec compliant and the site isn't (in which case this would be an advocacy matter), OR
- The code changes do not make us 100% spec compliant and it needs to be fixed on our end. We can look at what exactly would be needed for that once it is clear what the issue is.

The question is what -exactly- did the culprit commit change in behavior, did it have the desired effect re: the spec or not, and why?
And sorry @JustOff but I know of no-one better suited to the task than the person who implemented these changes. It falls under the label "owning the code you contribute".

**Comment by win7-7** [comment]
> The thing is this needs some time to research the issue. it's one of two scenarios:
> 
>     * The code changes made us spec compliant and the site isn't (in which case this would be an advocacy matter), OR
> 
>     * The code changes do not make us 100% spec compliant and it needs to be fixed on our end. We can look at what exactly would be needed for that once it is clear what the issue is.

The second scenario is correct it did not make UXP 100% spec compliant.

Fixed by https://bugzilla.mozilla.org/show_bug.cgi?id=1331864 

Implement URLSearchParams's sort()

This can be directly based to Mozilla and tested as working.

**Comment by mattatobin** [comment]
That doesn't look too evil.. Feel free to submit a PR.

**Comment by JustOff** [comment]
I spent all the time trying to figure out what's wrong with the existing code, but the solution lay just one step away. Nice catch, @win7-7!

**Comment by mattatobin** [comment]
@win7-7 That commit title is invalid.

**Comment by win7-7** [comment]
Pull Request done.

I split this to its own issue in https://github.com/MoonchildProductions/UXP/issues/1528 because that is maybe better way to do pull request than referring to this issue in pull request.

Commit title is changed to refer issue 1528. If commit title is still not suitable can somebody suggest better title for commit as that is what Mozilla used? Should it be Sort URLSearchParams prior to stringification for example as in https://github.com/whatwg/url/issues/26

**Comment by mattatobin** [comment]
You sure made a mess of things haven't you... Who told you to do that?

**Comment by mattatobin** [comment]
ONE.. Do not do anything unless you are explicitly told to. TWO do not try and mass close issues with a pull request. THREE.. Don't create new issues when we HAVE an ISSUE right here marked as a regression.

**Comment by mattatobin** [comment]
I'll land this personally. Give me test case instructions.

**Comment by win7-7** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/sort

Examples section in that document.

Run that in Scratchpad and see web console returning a=2&a=1&b=3&c=4 when opening web console in website.

This is way to verify URLSearchParams.sort() working outside of udemy website that I already tested as working after this patch.

Sorry for creating mess should have just asked what is correct commit title for you instead of creating mess when trying to fix that by splitting issues.

**Comment by mattatobin** [comment]
It's ok, I'm over being **_absolutely livid_** now ;)

Thanks for the work and the instructions. Will let you know!

**Comment by adamkenway007** [comment]
Wait,why this issue closed i am late here? is bug already fixed.i currently using pale moon 28.9.1
and this bug still occur,or probably may come on next update?

**Comment by mattatobin** [comment]
It will be in the next release.

**Comment by wolfbeast** [comment]
Reopened for uplift

**Comment by wolfbeast** [comment]
Uplifted in [ba5930cc8]

**Comment by adamkenway007** [comment]
> Uplifted in [[ba5930c](https://github.com/MoonchildProductions/UXP/commit/ba5930cc8ee975db4691f8a6d26503a9dae0135c)]
> 
> This should be in v28.9.3.1 (if we decide the webaudio regression warrants an out-of-band update) otherwise in v28.9.4

Thanks guys it's working now 😀
