### PR TITLE
Add dirty rect intersection checks so that we don't build unnecessary table part display items

### PR DESCRIPTION
**Pull request by win7-7**
Second optimization done to #1355.

Hit testing in large tables has become extremely slow. This PR will fix that.

This is based on https://bugzilla.mozilla.org/show_bug.cgi?id=1369141

This is a regression from Issue #146

Steps to reproduce:

   1.  Go to https://hg.mozilla.org/releases/mozilla-beta/annotate/cf76e00dcd6f/layout/painting/FrameLayerBuilder.cpp and wait for it to load.
  2.  Move your mouse around over the code on the page.
  3.  Watch how the row highlight changes.

It's very janky.

This second optimization does not change performance on Maze test but is performance improvement to regression in: https://hg.mozilla.org/releases/mozilla-beta/annotate/cf76e00dcd6f/layout/painting/FrameLayerBuilder.cpp also caused by #146

### CODE REVIEW

**Comment by wolfbeast** [comment]
Backed out for build bustage

```
 9:27.11 e:/mozdev/pmdev/platform/layout/tables/nsTableFrame.cpp(1241): error C2065: 'aDirtyRect': u
ndeclared identifier
 9:27.11 e:/mozdev/pmdev/platform/layout/tables/nsTableFrame.cpp(1241): error C2228: left of '.Inter
sects' must have class/struct/union
 9:27.11 e:/mozdev/pmdev/platform/layout/tables/nsTableFrame.cpp(1241): note: type is 'unknown-type'

 9:27.11 e:/mozdev/pmdev/platform/layout/tables/nsTableFrame.cpp(1254): error C2065: 'aDirtyRect': u
ndeclared identifier
 9:27.11 e:/mozdev/pmdev/platform/layout/tables/nsTableFrame.cpp(1254): error C2228: left of '.Inter
sects' must have class/struct/union
 9:27.11 e:/mozdev/pmdev/platform/layout/tables/nsTableFrame.cpp(1254): note: type is 'unknown-type'

 9:27.11 e:/mozdev/pmdev/platform/layout/tables/nsTableFrame.cpp(1324): error C2660: 'PaintRowGroupB
ackgroundByColIdx': function does not take 7 arguments
 9:27.11 e:/mozdev/pmdev/platform/layout/tables/nsTableFrame.cpp(1342): error C2660: 'PaintRowGroupB
ackgroundByColIdx': function does not take 7 arguments
 9:27.12
 9:27.14 In the directory  /e/mozdev/obj-pm-x86-unstable/layout/tables
 9:27.14 The following command failed to execute properly:
 9:27.14 e:/mozdev/obj-pm-x86-unstable/_virtualenv/Scripts/python.exe -m mozbuild.action.cl d:/VS201
5/VC/BIN/amd64_x86/cl.EXE -FoUnified_cpp_layout_tables0.obj -c -Ie:/mozdev/obj-pm-x86-unstable/dist/
stl_wrappers -DNDEBUG=1 -DTRIMMED=1 -DDEBUG_TABLE_STRATEGY_off -DSTATIC_EXPORTABLE_JS_API -DMOZ_HAS_
MOZGLUE -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL -Ie:/mozdev/pmdev/platform/layout/tables -Ie:/mozdev/ob
j-pm-x86-unstable/layout/tables -Ie:/mozdev/pmdev/platform/intl/unicharutil/util -Ie:/mozdev/pmdev/p
latform/layout/base -Ie:/mozdev/pmdev/platform/layout/generic -Ie:/mozdev/pmdev/platform/layout/styl
e -Ie:/mozdev/pmdev/platform/layout/xul -Ie:/mozdev/pmdev/platform/dom/base -Ie:/mozdev/pmdev/platfo
rm/dom/html -Ie:/mozdev/obj-pm-x86-unstable/dist/include -Ie:/mozdev/obj-pm-x86-unstable/dist/includ
e/nspr -Ie:/mozdev/obj-pm-x86-unstable/dist/include/nss -MD -FI e:/mozdev/obj-pm-x86-unstable/mozill
a-config.h -DMOZILLA_CLIENT -TP -nologo -wd5026 -wd5027 -Zc:sizedDealloc- -wd4752 -wd4091 -wd4577 -D
_HAS_EXCEPTIONS=0 -W3 -Gy -Zc:inline -utf-8 -arch:SSE2 -FS -Gw -wd4251 -wd4244 -wd4267 -wd4345 -wd43
51 -wd4800 -wd4595 -we4553 -GR- -Zi -O2 -Oy- -Fdgenerated.pdb e:/mozdev/obj-pm-x86-unstable/layout/t
ables/Unified_cpp_layout_tables0.cpp
 9:27.16 e:/mozdev/pmdev/platform/config/rules.mk:884: recipe for target 'Unified_cpp_layout_tables0
.obj' failed
 9:27.16 mozmake.EXE[4]: *** [Unified_cpp_layout_tables0.obj] Error 1
 9:27.16 e:/mozdev/pmdev/platform/config/recurse.mk:71: recipe for target 'layout/tables/target' fai
led
```
